services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      GF_INSTALL_PLUGINS: 'https://github.com/elohmeier/rqlite-datasource/releases/download/v1.1.5/g42-rqlite-datasource-1.1.5.zip;g42-rqlite-datasource'
